---
title: Jelly
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
gems:
- bourbon
- neat
sass:
  style: compressed
description: An example site
baseurl: "/jelly"
markdown: kramdown
prose:
  ignore:
  - _includes
  - assets
  - _assets
  - _layouts
  - _plugins
  - "/.jekyll-metadata"
  - feed.xml
  media: img
  metadata:
    _posts:
    - name: date
      field:
        label: Date
        element: text
        value: CURRENT_DATETIME
    - name: published
      field:
        label: Published
        element: checkbox
        value: false
    - name: layout
      field:
        element: hidden
        value: default
